---
- name: setup | ensure {{ tomcat_install_path }} exists
  ansible.builtin.file:
    path: "{{ tomcat_install_path }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0755
    state: directory

- name: setup | unarchive apache-tomcat-{{ tomcat_version }}.tar.gz at {{ tomcat_install_path }}
  ansible.builtin.unarchive:
    src: "{{ tomcat_download_url }}/tomcat/tomcat-{{ tomcat_version.split('.')[0] }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_path }}"
    remote_src: true
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    creates: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"

- name: setup | fix parent folder permissions
  ansible.builtin.file:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    recurse: yes

- name: setup | deploy drivers
  ansible.builtin.get_url:
    url: "{{ item }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    dest: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/lib/"
    mode: 0640
  with_items: "{{ tomcat_drivers }}"
