---
- name: env | determine if {{ tomcat_user }} exists
  ansible.builtin.getent:
    database: passwd
    key: "{{ tomcat_user }}"
    fail_key: false

- name: setup | create system user
  ansible.builtin.user:
    name: "{{ tomcat_user }}"
    home: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
    create_home: no
    system: yes
    state: present
  when: getent_passwd[tomcat_user] == none

- name: Check if tomcat is already installed
  ansible.builtin.stat:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
  register: is_installed

- name: Give up if installation already exists
  ansible.builtin.debug:
    msg: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }} already exists and will not be overwritten"
  when: is_installed.stat.exists and not tomcat_force_install

- name: Install tomcat {{ tomcat_version }}
  ansible.builtin.import_tasks: install.yml
  when: not is_installed.stat.exists or tomcat_force_install

- name: Initialize tomcat configuration
  ansible.builtin.import_tasks: init.yml
  when: not is_installed.stat.exists or tomcat_force_install
